name: proyecto_app
description: "AnkaraBurgerApp."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  uuid: ^4.5.1
  path_provider: ^2.1.1
  # esc_pos_printer: ^4.0.4
  # esc_pos_utils: ^1.1.0
  pdf: ^3.10.4
  printing: ^5.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/database/
